GET http://localhost:3000/comments/6085672c99f1447844dc6569

###
GET http://localhost:3000/comments/6085659699f1447844dc6568

###
GET http://localhost:3000/comments/6085659699f1447844dc6569

###
POST http://localhost:3000/comments/6085672c99f1447844dc6569
Content-Type: application/json

{
    "nick": "michal",
    "title": "Nie podobało mi się",
    "content": "W parku były śmieci!!!",
    "rate": 3,
    "dateOfVisit": "2021-04-21T13:43:04.621Z"
}

###
POST http://localhost:3000/comments/6085659699f1447844dc6568
Content-Type: application/json

{
    "nick": "andrzej",
    "title": "Fajne miejsce",
    "content": "Ciekawa ekspozycja tylko trzeba dużo chodzić",
    "rate": 4,
    "dateOfVisit": "2021-04-14T13:43:04.621Z"
}


###
POST http://localhost:3000/comments/6085672c99f1447844dc6569
Content-Type: application/json

{
    "title": "Nie podobało mi się",
    "content": "W parku były śmieci!!!",
    "rate": 3,
    "dateOfVisit": "2021-04-21T13:43:04.621Z"
}

###
DELETE http://localhost:3000/comments/60857251778a447dbcacd68c

###
DELETE http://localhost:3000/comments/6085728e27f4ad755820246a