GET http://localhost:3000/places

###
GET http://localhost:3000/places?city=Warszawa

###
GET http://localhost:3000/places?city=Granica

###
GET http://localhost:3000/places?name=Urodzenia

###
POST http://localhost:3000/places
Content-Type: application/json

{
    "name": "Dom Urodzenia Fryderyka Chopina",
    "description": "Dom Urodzenia Fryderyka Chopina – muzeum biograficzne Fryderyka Chopina w Żelazowej Woli, w skład którego wchodzi oficyna (tzw. dworek) oraz 7-hektarowy park krajobrazowy nad rzeką Utratą. Dwór wraz z parkiem jest oddziałem Muzeum Fryderyka Chopina w Warszawie zarządzanego przez Narodowy Instytut Fryderyka Chopina.",
    "city": "Żelazowa Wola",
    "street": "Żelazowa Wola 15",
    "lat": 52.2571,
    "lon": 20.3109,
    "costToVisit": 30,
    "timeToVisit": 150

}

###
POST http://localhost:3000/places
Content-Type: application/json

{
    "name": "Skansen budownictwa puszczańskiego w Granicy",
    "description": "Skansen budownictwa puszczańskiego – niewielki skansen (trzy zagrody) we wsi Granica k. Kampinosu.",
    "city": "Granica",
    "street": "05-085 Granica",
    "lat": 52.28802,
    "lon": 20.448558,
    "costToVisit": 0,
    "timeToVisit": 60

}

###
GET http://localhost:3000/places/6085672c99f1447844dc6569


###
PUT http://localhost:3000/places/6085672c99f1447844dc6569
Content-Type: application/json

{
    "name":"Dom Urodzenia Fryderyka Chopina",
    "description":"Dom Urodzenia Fryderyka Chopina – muzeum biograficzne Fryderyka Chopina w Żelazowej Woli, w skład którego wchodzi oficyna (tzw. dworek) oraz 7-hektarowy park krajobrazowy nad rzeką Utratą. Dwór wraz z parkiem jest oddziałem Muzeum Fryderyka Chopina w Warszawie zarządzanego przez Narodowy Instytut Fryderyka Chopina.",
    "city":"Stalowa Wola",
    "street":"Żelazowa Wola 15",
    "lat":52.2571,
    "lon":20.3109,
    "costToVisit":50,
    "timeToVisit":180
}

